### ISSUE TITLE
Ectoplasm pools generation 

### ISSUE THREAD

**Issue by Technomancer666** [ThatJadenXgamer/Jadens-Nether-Expansion#100]
They are currently generating way to frequently induce of the walls and ceilings.

**Comment by Qwerty97475** [comment]
![2024-12-05_15 20 57](https://github.com/user-attachments/assets/414851b2-f6ff-401f-aab3-057baeff081a)
Yeah these pools are far too common

**Comment by ThatJadenXgamer** [comment]
Fixed in 2.1.4
