### ISSUE TITLE
Load and chunk world freeze issue with Untamed WIlds

### ISSUE THREAD

**Issue by MrFreddle** [ThatJadenXgamer/Jadens-Nether-Expansion#105]
About the most random mix of mods to not work with one another.

But as of 2.1.1 and beyond, when Untamed Wilds is also in the modpack it gets new worlds to get stuck at 0% when generating.
Not a direct crash but just a freeze that needs to be closed with task manager.

Already loaded worlds seem to work find when within already loaded chunks, but when loading anything new everything seems to freeze completely. So any and all chunk generation is a little wacky.

This could be something entirely not on Jaden's Nether Expansion at all but thought I'd be worth reporting given 2.1.0 and below work a okay.

**Comment by ThatJadenXgamer** [comment]
please send a log

**Comment by MrFreddle** [comment]
> please send a log

**Comment by MrFreddle** [comment]
> please send a log

Oops sorry

Anyways

Apologies I'll send it here.

This is the most recent log. Can't get a crash log. Sadly just a normal log. Sending latest logs as of testing right now.

[latest.log](https://github.com/user-attachments/files/17985338/latest.log)

[2024-12-02-6.log](https://github.com/user-attachments/files/17985361/2024-12-02-6.log)

**Comment by ThatJadenXgamer** [comment]
yeah it seems a mixin from JNE is causing this, I'll get this fixed asap

**Comment by MrFreddle** [comment]
> yeah it seems a mixin from JNE is causing this, I'll get this fixed asap

Cheers
