### ISSUE TITLE
[PC Java Forge 1.20.1- 2.1.3] crash on startup, most likely incompatibility issue with other mods.

### ISSUE THREAD

**Issue by NotYourLifeline** [ThatJadenXgamer/Jadens-Nether-Expansion#107]
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

crash log:
[crash-2024-12-09_04.12.28-client.txt](https://github.com/user-attachments/files/18053709/crash-2024-12-09_04.12.28-client.txt)

modlist:
![2024-12-09_04 23 33](https://github.com/user-attachments/assets/3e1c527f-85f7-4dd1-9ccc-e9ad25b4fb14)

also Enhanced Celestials causes the crash as well, and the game runs normally without problem when both Enhanced Celestials and Nether Expansion are disabled.

**Comment by ThatJadenXgamer** [comment]
the log doesn't say anything about JNE. the issue is being caused by another mod
please find it and report it to their devs ^^
