### ISSUE TITLE
Incompatibility with Call of Yucatan

### ISSUE THREAD

**Issue by MarizPOG** [ThatJadenXgamer/Jadens-Nether-Expansion#108]
Local server is not responding when you are trying to generate chunks with structure from Call of Yucatan.  
https://mclo.gs/XgYLL9H
https://github.com/user-attachments/assets/086d0285-a528-4920-9914-31e842e91ca7

**Comment by ThatJadenXgamer** [comment]
Fixed in 2.1.4
