### ISSUE TITLE
Chunks Freeze Issue

### ISSUE THREAD

**Issue by SHXRKIEgg** [ThatJadenXgamer/Jadens-Nether-Expansion#109]
**Install these mods**
![image](https://github.com/user-attachments/assets/29d3c6d2-a62c-422c-9d60-012b6e988c61)

**Load Seed: 4312595124482500659 > TP to 150 120 -4013 > Chunks stop loading**
I believe its NetherExp causing an issue with Removing behaviors from Alexs Mobs
`netherexp$customRemoveBehavioralexsmobs@1.22.9/com.github.alexthe666.alexsmobs.world.FeatureLeafcutterAnthill.m_142674_(FeatureLeafcutterAnthill.java:70)`

Chunks stop loading 
![image](https://github.com/user-attachments/assets/9802b78f-ce8b-4fb3-827f-6de1c9a49a9d)

Here is a log from my BMC4 testing where it just infinite saving and quitting and doesnt show proper logs for the issue
[2024-12-11-3.log](https://github.com/user-attachments/files/18089404/2024-12-11-3.log)
Started happening with version 2.1.1

**Comment by ThatJadenXgamer** [comment]
Fixed in 2.1.4
