### ISSUE TITLE
Soul soil layers, soul slate slabs, soul slate brick slabs, and suspicious soul sand, burn normal fire

### ISSUE THREAD

**Issue by thelegitdolt** [ThatJadenXgamer/Jadens-Nether-Expansion#12]
<img width="1512" alt="Screenshot 2024-10-01 at 8 42 24 PM" src="https://github.com/user-attachments/assets/58ac4f83-39e4-4386-99a1-ce200e2c99a8">

**Comment by ThatJadenXgamer** [comment]
it's actually intentional for Suspicious Soul Sand, but not the others
I'll get this fixed!
