### ISSUE TITLE
Nether’s Delight & My Nether’s Delight Compatibility

### ISSUE THREAD

**Issue by RealCipherPool** [ThatJadenXgamer/Jadens-Nether-Expansion#121]
Can you make the Hoglin drop both Hogham and Hoglin Loin when the Hoglin is slain?

Both Nether’s Delight and My Nether’s Delight are two separate mods.

**Comment by ThatJadenXgamer** [comment]
it's already been implemented with My Nether's Delight
regular Nether's Delight will not receiving this change since it's a discontinued mod
