### ISSUE TITLE
(Rusty) Netherite Grate Block Not Compatible with Non Vanilla/JNE Fluids.

### ISSUE THREAD

**Issue by ghost** [ThatJadenXgamer/Jadens-Nether-Expansion#122]
Neither the netherite grate block nor its rusty counterpart can be fluid-logged with other modded fluids as (to my knowledge) it only has block-states for air, water, lava, and the mod's ectoplasm fluid. 

Some notable ones I found are blood and liquid null from Biomes O' Plenty and the virulent mix from The Undergarden mod, to name a few.

**Comment by ThatJadenXgamer** [comment]
Unfortunately it's really difficult to code these to be compatible with all fluids and maintain support for it.
which is why they only support Vanilla and JNE fluids
