### ISSUE TITLE
Soul Fire not burning and Soul Speed not working on Suspicious Soul Sand, Soul Jack o' Lanterns and Burning Skull Blocks.

### ISSUE THREAD

**Issue by Tamakii-2005** [ThatJadenXgamer/Jadens-Nether-Expansion#124]
Perhaps this is intended, at least with Skull Blocks and Soul Jack/Ghoul o' Lanterns, but Suspicious Soul Sand not working with none of these seems a tad wack.

As an extra, though I think this cannot be fixed, soul speed does not work with some non-full blocks such as slabs, soul soil layers or soul candles.

![2024-12-26_13 03 44](https://github.com/user-attachments/assets/8b5b68ad-4aa8-4d79-9c99-5c2246da2269)
![2024-12-26_13 04 04](https://github.com/user-attachments/assets/32bc9459-dfe9-4205-9f23-5072bb3bb8b1)
![2024-12-26_13 04 15](https://github.com/user-attachments/assets/d649dd1c-8efa-489a-b5ec-fc75c761f1eb)

**Comment by ThatJadenXgamer** [comment]
all of these are intentional
Suspicious Soul Sand was made to burn normal fire since it makes them "suspicious"
soul variants of the pumpkins and skull blocks shouldn't technically burn soul fire since it's only a corresponding torch placed inside it
