### ISSUE TITLE
Excessive server load from the netherexp mod

### ISSUE THREAD

**Issue by AxelEncore** [ThatJadenXgamer/Jadens-Nether-Expansion#126]
Hi!

I have a problem that on my server constantly, when players over 15+, the server begins to seriously skip ticks, dropping to 10-15 TPS
Surveillance server on ryzen 9 and half of it won't load, I realized that the problem was netherexp only because spark showed me these statistics. Tell me why this might change?

Thank you

I'm using Forge 1.20.1 47.2.30

Jadens-Nether-Expansion-2.0.1-Forge.jar

![sdsddssd](https://github.com/user-attachments/assets/b22d5f4a-7a5e-4e99-97e9-4ddf599b58ef)

**Comment by AxelEncore** [comment]
![{AC43B4CB-260F-4C9C-8F53-E1FEC3D22D7B}](https://github.com/user-attachments/assets/c6fd9de8-bbd3-46e7-866e-0b9bf58903a8)

**Comment by ThatJadenXgamer** [comment]
why are you on 2.0.1?
update the mod to 2.1.6 (the latest). this bug was fixed a long time ago
