### ISSUE TITLE
Pump Charge upgrade templates do not have a duplication recipe

### ISSUE THREAD

**Issue by thelegitdolt** [ThatJadenXgamer/Jadens-Nether-Expansion#13]

**Comment by ThatJadenXgamer** [comment]
While it was intentional for it not have a duplication recipe I'm going to give it one now for QoL sake since constantly doing treacherous candles for it does get pretty tedious

thanks for the suggestion!

**Comment by ThatJadenXgamer** [comment]
![image](https://github.com/user-attachments/assets/84097785-04f9-4f27-b8f3-c70052a15499)
