### ISSUE TITLE
Will O' Wisps Can Damage Endermen

### ISSUE THREAD

**Issue by Sydokiddo** [ThatJadenXgamer/Jadens-Nether-Expansion#18]
Pretty self explanatory from the title, Endermen teleport from other projectiles and don't take damage (including the Shotgun Fist's projectiles) however they don't do this for Will O' Wisps!

**Comment by ThatJadenXgamer** [comment]
I wasn't able to recreate this issue, endermen always teleported before the wisps hit for me
