### ISSUE TITLE
Odd Crash on loading phase: One of more entry values did not copy to the correct id

### ISSUE THREAD

**Issue by Cricket742** [ThatJadenXgamer/Jadens-Nether-Expansion#22]
Not entirely sure this is this mods problem, as I am tinkering with a "how many mods can I add before it breaks" modpack, but i did only get this error when I added this mod, and it only went away once I removed it. here are the logs and crash reports: 
[crash-2024-10-03_12.31.34-client.txt](https://github.com/user-attachments/files/17247303/crash-2024-10-03_12.31.34-client.txt)
[latest.log](https://github.com/user-attachments/files/17247310/latest.log)

 
If this is another mod's problem I apologize in advance

**Comment by ThatJadenXgamer** [comment]
This log doesn't give any specific details so it's difficult to tell what caused this crash
it seems like a forge issue? not sure

**Comment by Cricket742** [comment]
Yeah I was having trouble figuring it out too. I'll test it out some more with the old/ divide your mods in two and see what happens trick

Update: It's diagonal fences causing the error. I'm also getting some other errors with different mods so I'm going to do more testing

Update: The odd thing is with just this mod and diagonal fences installed, minecraft loads fine, I'm doing more testing to try and figure out the combination of mods. All of the mods load fine together without this mod enabled, but some combination of them is causing different errors.

**Comment by Cricket742** [comment]
Ok so the main culprit is glassential-renewed. I have no idea why, or even if diagonal fences augments the error at all, but i don't think it's a huge deal, but this mod works with diagonal fences and everything else if there's no glassential-renewed. sorry for bothering you

**Comment by ThatJadenXgamer** [comment]
it seems there is something wrong with glassential-renewed, since multiple other people have reported this incompatibility too
from my investigation I found that they are registering custom sounds in a very weird way which is causing incompatibilities with JNE

**Comment by ThatJadenXgamer** [comment]
I'm gonna be closing this issue as a duplicate. you can continue discussion in #26 since it was linked in glassential-renewed's issue tracker and keeping everything in one place would be easier to manage
