### ISSUE TITLE
incompatible with snow real magic mod

### ISSUE THREAD

**Issue by lzm11111111** [ThatJadenXgamer/Jadens-Nether-Expansion#23]
Placing a soul soil layer will become snow layer when have snow real magic Installed

**Comment by ThatJadenXgamer** [comment]
That's odd, I'll look into it

**Comment by wawwior** [comment]
This is probably due to Snow! Real Magic! having a mixin into SnowLayerBlock, affect all subclasses including SoulSoilLayerBlock, which extends aforementioned SnowLayerBlock. I'm not sure how this affects the placement yet, but the compatibility is most likely to be requested on their side.

**Comment by wawwior** [comment]
Its this one right here officer:
https://github.com/Snownee/SnowRealMagic/blob/1.20-fabric/src/main/java/snownee/snow/Hooks.java#L486
