### ISSUE TITLE
Showing admiration and appreciation

### ISSUE THREAD

**Issue by Cixon** [ThatJadenXgamer/Jadens-Nether-Expansion#25]
This mod is wonderful and I cannot wait to see what else you have in store!
There’s still a lot of work to be made I’d imagine but I’d love to see this mod for 1.21.1 NeoForge whenever this is possible, please and thank you! 🙏

**Comment by ThatJadenXgamer** [comment]
Thanks but this is the Incorrect use of Issue Tracker, please don't use it for requesting updates. 
I will eventually be updating to 1.21 and NeoForge but not anytime soon
