### ISSUE TITLE
Glassential Renewed Incompatibility

### ISSUE THREAD

**Issue by mxnmnm** [ThatJadenXgamer/Jadens-Nether-Expansion#26]
This crash happens on launch and involves multiple mods that are mentioned in the crash report. Some of these mods can be used with this mod together but when they are all combined the crash happens. I'm not sure if other installed mods are impacting things, but it is able to boot fine when either this mod is removed or some of the mods in the crash report are removed, so I would say it is unlikely other mods are contributing. An important thing to note is that I enabled dynamic resources in modernfix. 

Here is the crash: https://gist.github.com/mxnmnm/da437d837b42f3e4f78f173c1240115d

If you need anymore info please let me know.

**Comment by mxnmnm** [comment]
After some more testing glassential renewed seems to be the problem. Here is a much less cluttered crash report: https://gist.github.com/mxnmnm/d7ddc301071b528251d4c995efa66ddb

**Comment by ThatJadenXgamer** [comment]
Yeah it might be an issue on Glassential Renewed's side
they register their sounds in a very weird way and for some reason seems to be causing conflicts with JNE

**Comment by ThatJadenXgamer** [comment]
glassential fixed the issue
