### ISSUE TITLE
Incompatibility with Oculus for Forge

### ISSUE THREAD

**Issue by LanTao26** [ThatJadenXgamer/Jadens-Nether-Expansion#28]
I was trying to run the mod with its dependencies and Complementary shaders alongside Oculus, but the game kept crashing and giving me the following log:

[---- Minecraft Crash Report ----.txt](https://github.com/user-attachments/files/17266962/----.Minecraft.Crash.Report.----.txt)

**Comment by ThatJadenXgamer** [comment]
This crash log does not give much information, could you also send me the regular log file?

**Comment by LanTao26** [comment]
I apologize for taking so long to answer, had a crazy week. Anyway it seems like you have already solved the problem and JNE now can load with Oculus
