### ISSUE TITLE
Pale soul slate and regular soul slate blockset can only be mined with iron or higher

### ISSUE THREAD

**Issue by asdasdasadg** [ThatJadenXgamer/Jadens-Nether-Expansion#29]

**Comment by ThatJadenXgamer** [comment]
Intentional

**Comment by asdasdasadg** [comment]
> Intentional

soul slate bricks can be mined by any tier then

**Comment by ThatJadenXgamer** [comment]
yeah, it's sort of for convenience while building
regular and pale soul slate requires iron to nudge the player to get iron before entering the nether and to make nether-only survival more interesting
