### ISSUE TITLE
Sanctums interfere with the generation of other structures

### ISSUE THREAD

**Issue by FunniMCEnthusiast** [ThatJadenXgamer/Jadens-Nether-Expansion#3]
I noticed that sanctums can mess with the generation of both vanilla and JNE structures. I found a campsite generating in the middle of a sanctum, another campsite partially floating above one, a regular fossil completely floating in the air, and multiple fossils that generated inside of a sanctum but seemingly aren't there at the same time (Teleporting to them just brings me to empty space if that makes sense)

**Comment by ThatJadenXgamer** [comment]
due to how minecraft generates structures, conflicts like these are unavoidable unfortunately. but I'll try and see if I can at least prevent mega fossils from generating here
