### ISSUE TITLE
Large magma cube texture bug

### ISSUE THREAD

**Issue by Technomancer666** [ThatJadenXgamer/Jadens-Nether-Expansion#31]
The texture of the large magma cube appears to not be lining up correctly and it makes it look kind of choppy and shifted in places.

**Comment by ThatJadenXgamer** [comment]
could you provide some screenshots?

**Comment by MarshMiloMoon** [comment]
seems like the medium magma cube also has this issue
![IMG_4778](https://github.com/user-attachments/assets/e105f370-d469-470f-9bbe-0460184bb1f3)
![IMG_4779](https://github.com/user-attachments/assets/1c37d527-cfed-449e-9be5-20a87bcd78ca)
