### ISSUE TITLE
With Quark, sanctum compass shows arrow icon

### ISSUE THREAD

**Issue by MarshMiloMoon** [ThatJadenXgamer/Jadens-Nether-Expansion#33]
When the Sanctum Compass is held, an arrow icon appears as if the compass uses it.
I’m assuming the proper icon for this would be Wraithing Flesh, since it uses that?
![image](https://github.com/user-attachments/assets/255d0c4c-b2db-4e94-b9ff-215e01b5450a)

**Comment by ThatJadenXgamer** [comment]
okay so after doing some more testing, quark shows the arrow for everything if you're in creative and don't have wraiting flesh in your inventory. otherwise it shows wraithing flesh there like normal
