### ISSUE TITLE
is this incompatible with Optifine, my game wont launch with it?  

### ISSUE THREAD

**Issue by marco2651** [ThatJadenXgamer/Jadens-Nether-Expansion#35]
@ThatJadenXgamer is this incompatible with Optifine, my game wont launch with it?

**Comment by wawwior** [comment]
Virtually nothing is compatible with Optifine, try [Sodium](https://modrinth.com/mod/sodium) + [Indium](https://modrinth.com/mod/indium)

**Comment by marco2651** [comment]
ill give it a go, thankyou

**Comment by ThatJadenXgamer** [comment]
Optifine incompatibilities are inevitable, and us mod developers can't do anything about it because Optifine's code is closed source

**Comment by marco2651** [comment]
thanks for confirming
