### ISSUE TITLE
Config files issue: gold_tools_speed was corrected from 16.0 to its default, 16.0

### ISSUE THREAD

**Issue by wil05** [ThatJadenXgamer/Jadens-Nether-Expansion#38]
ive got a modpack that i made, and a server i run that modpack on that has Jadens Nether Expansion on it and have recently updated the pack to include the latest version of the mod and since updating the whole server log is filled with the following error:

```
[13:06:23] [pool-5-thread-1/WARN]: Configuration file /home/container/./config/netherexp-common.toml is not correct. Correcting
[13:06:23] [pool-5-thread-1/WARN]: Incorrect key experimental.gold_tools_speed was corrected from 16.0 to its default, 16.0.
```
![image](https://github.com/user-attachments/assets/724106c7-c79c-44f6-a46d-2ce8becbd672)

The server does start but im unable to join the server, though im not sure if that is caused by this but its kinda hard to read the logs when this message is being spammed, ive tried editing and straight up deleting the config file but nothing is working.
Also a player doesnt have to join for the error messages to appear they happen when they load on the server startup and keep spamming the console whether a player is online or not

I can open and run single player worlds fine on the client but when i launch the server that error message spams the console

If i edit the `gold_tools_speed` in the config it reverts it back to 16 as well so editing it does nothing and deleting it just does the same thing. 
Ive got the `enable_gold_tweaks` set to false as well anyways 
Ive also just tried deleting that section from config file and it just regenerates when launching the server

After spamming the chat it also makes several backup files of the config file
![image](https://github.com/user-attachments/assets/fc112a1e-8b80-439a-9250-eba6095e37c7)

Heres the latest log as well
[latest (1).log](https://github.com/user-attachments/files/17301740/latest.1.log)

**Comment by KrokusAstra** [comment]
Same. It's just trashed my console with it. Latest log file already had 90% of it. I play on single player mod and have it.
![изображение_2024-10-09_172533746](https://github.com/user-attachments/assets/90ffeb28-c916-433f-9db8-2ff241a084ea)

**Comment by ThatJadenXgamer** [comment]
It's going to be fixed in the upcoming halloween update but for now you can safely dismiss the warns as it should still let you join and play the world with no issue
