### ISSUE TITLE
Crimson foliage generation 

### ISSUE THREAD

**Issue by Technomancer666** [ThatJadenXgamer/Jadens-Nether-Expansion#4]
Crimson sprouts and beards are not generating naturally in the crimson forest biome.

**Comment by Xenoraptor10** [comment]
Same for me also(for Forge)

**Comment by ThatJadenXgamer** [comment]
Nether Wart Beards aren't suppose to naturally generate but Sprouts not generating is a bug. I'll get this fixed soon!
