### ISSUE TITLE
Progressive Archery crash

### ISSUE THREAD

**Issue by GameAnt** [ThatJadenXgamer/Jadens-Nether-Expansion#44]
Whenever killing certain mobs from Jadens Nether Expansion mod with progressive archery mod items game crashes.

(Edit 1)
I have only come across one mob that causes the crash so far and that one would be the Apparition
There was another mob I killed that caused the crash but thats from an entirely different mod

And for the weapon it is any bow when Jadens nether expansion and progressive archery mod are mixed

(edit 2)
The only two mobs in the pack that cause the crash are the Apparition and the Wisp.

**Comment by wawwior** [comment]
Can you give more information? (Which mobs, which items)
Also a crashlog would be nice

**Comment by GameAnt** [comment]
I have only come across one mob that causes the crash so far and that one would be the Apparition
There was another mob I killed that caused the crash but thats from an entirely different mod

**Comment by Wawwior** [comment]
Using Progressive Archery 1.1.3.a-1.20.1 and the last Jaden's Nether Expansion build, i could not reproduce this issue.

**Comment by Wawwior** [comment]
@ThatJadenXgamer

**Comment by wawwior** [comment]
Using Progressive Archery 1.1.3.a-1.20.1 and the last Jaden's Nether Expansion build, i could not reproduce this issue.
@ThatJadenXgamer what do?

**Comment by ThatJadenXgamer** [comment]
they messaged me on discord a few days ago and provided more information there,
It seems their bow had Piercing and was the cause for this crash not progressive archery

the piercing crash was fixed earlier today
![image](https://github.com/user-attachments/assets/6b8b2406-4d7d-41e3-950c-157268e34a07)
