### ISSUE TITLE
Modpack Crashing on load with JNE

### ISSUE THREAD

**Issue by MangoMonke** [ThatJadenXgamer/Jadens-Nether-Expansion#53]
Trying to download JNE onto a modpack, but it seems to always crash immediately on startup.

https://mclo.gs/hR6tYfh - Crashlog here

There are other errors, but they seem to be fine as they don't stop the modpack from loading.  As soon as I add JNE it crashes so I figure this is the issue.  From the logs, it seems to be something with arrows, possibly with the ectoplasm arrows (?), unsure.

Seems to be a conflict with JNE and PuzzlesLib.

**Comment by wawwior** [comment]
Mixin error, we can try mixin extras and otherwise its puzzle lib fault
