### ISSUE TITLE
Option to disable potion stack changes

### ISSUE THREAD

**Issue by platypushasnohat** [ThatJadenXgamer/Jadens-Nether-Expansion#54]
Currently the only option for potion stack sizes is changing the stack size of all potions. This config option seems to override mods like KubeJS when changing stack sizes with that. It would be nice to have the option to disable the stack size changes and have different stack sizes for different potion types.

**Comment by thelegitdolt** [comment]
+1. This mod makes caverns and chasms tether potions stack which uh.. 

<img width="645" alt="Screenshot 2024-10-24 at 9 34 11 PM" src="https://github.com/user-attachments/assets/1789d176-e811-4c5d-847b-3bd7e3e95b88">

**Comment by ThatJadenXgamer** [comment]
that's odd, I'll have it checked
