### ISSUE TITLE
Usage of @Redirect in AbstractArrowMixin crashes with mods that mix into AbstractArrow#tick()

### ISSUE THREAD

**Issue by Arna577** [ThatJadenXgamer/Jadens-Nether-Expansion#55]
The injector in question should be replaced with an @Inject or MixinExtras' @WrapOperation, as both of those allow stacking of Mixins.

**Comment by ThatJadenXgamer** [comment]
Are there any mods which you know that mix into AbstractArrow#tick so I can test it in my dev env?

**Comment by Arna577** [comment]
The mod i work on, https://www.curseforge.com/minecraft/mc-mods/jcraft-eyes-of-ender, does this for gravity manipulation support.

**Comment by ThatJadenXgamer** [comment]
dunno why it didn't automatically close the issue
but yeah it seems to now work with your mod and others which mix into AbstractArrow#tick()
