### ISSUE TITLE
Incompat with Nether's Delight and My Nether's Delight

### ISSUE THREAD

**Issue by Dianuniverse27** [ThatJadenXgamer/Jadens-Nether-Expansion#57]
Killing an Hoglin with Farmer's Delight knife only drops Jaden Hoglin meat replacing Hoglin Loin from Nether's Delight and My Nether's delight.

**Comment by ThatJadenXgamer** [comment]
this is already fixed in the upcoming halloween patch coming this week
for now you can disable the hogham drop in configs
