### ISSUE TITLE
Player can use bone meal on soul swirls but it does nothing

### ISSUE THREAD

**Issue by 0Starocean0** [ThatJadenXgamer/Jadens-Nether-Expansion#64]
As the title, player can use bone meal on soul swirls but it does nothing

**Comment by ThatJadenXgamer** [comment]
what is `soul_swirls_bone_meal_behavior` set to in your config.toml file?

**Comment by 0Starocean0** [comment]
> what is `soul_swirls_bone_meal_behavior` set to in your config.toml file?

It's `DUPLICATES`

**Comment by ThatJadenXgamer** [comment]
I forgot that I made it so soul swirls can only duplicate when it's on a soul sand/soul soil blocks when bone mealed
it's intended behavior
