### ISSUE TITLE
Missing fluid texture and lang entry for Ectoplasm

### ISSUE THREAD

**Issue by VoidLeech** [ThatJadenXgamer/Jadens-Nether-Expansion#71]
Mod version 2.1.0
Despite the in-world fluid having a texture, the fluid has no texture inside jei (~~there's only an ectoplasm texture in the resources/assets/netherexp/textures/blocks directory~~ (adding a texture to the fluids directory didn't change anything so this likely isn't the cause unless there's a nonsensible id that I didn't check))
There's also no language entry defined.
![image](https://github.com/user-attachments/assets/656a0501-c5a1-41ea-9569-db8da90178ea)

**Comment by wawwior** [comment]
i knew about the language entry, but uh the texture is perfectly fine in EMI e.g. so that might be a jei thing

**Comment by ThatJadenXgamer** [comment]
I have no idea what's causing the texture thing on JEI but the lang file has been implemented
