### ISSUE TITLE
Gargoyle things do not have soul fire

### ISSUE THREAD

**Issue by thelegitdolt** [ThatJadenXgamer/Jadens-Nether-Expansion#75]
<img width="1512" alt="Screenshot 2024-10-30 at 1 42 20 PM" src="https://github.com/user-attachments/assets/a7d3dad9-79ab-4bce-8297-5957d2c1f3f0">

**Comment by ThatJadenXgamer** [comment]
I didn't know they could even be lit on fire lol, I'll get this fixed

**Comment by thelegitdolt** [comment]
yeah some of the gargoyles that definitely don't like you shoudl be able to light them on fire, espeically the flower one. I think it's becasue their hitboxes uses full blocks which might be weird

**Comment by thelegitdolt** [comment]
<img width="1512" alt="Screenshot 2024-10-31 at 10 14 44 AM" src="https://github.com/user-attachments/assets/65e7549a-c5a9-4c17-8c07-47126d4aa571">
wow
