### ISSUE TITLE
FEATURE REQUEST: Fluid interactions with alex mobs fluids

### ISSUE THREAD

**Issue by thelegitdolt** [ThatJadenXgamer/Jadens-Nether-Expansion#77]
<img width="1512" alt="Screenshot 2024-10-31 at 10 16 08 AM" src="https://github.com/user-attachments/assets/5dcb28e5-4d88-47b4-9ed9-12f43c053fdf">

- Purple Soda buckets always transforms fluids into their respective color of rock candy, so water transforms into Blue Rock Candy, Lava into Orange, Acid into Green, etc. It would be nice if it transformed ectoplasm into Cyan
- Acid buckets transforms water into Mud, lava turns it into radrock, though i'm not sure what it would do in contact with ectoplasm

**Comment by ThatJadenXgamer** [comment]
I'll add this with the december compat update

**Comment by ThatJadenXgamer** [comment]
has been added in the upcoming 2.2.0 update
