### ISSUE TITLE
Unexpected bow behaviour when used with other mods

### ISSUE THREAD

**Issue by Jirickal** [ThatJadenXgamer/Jadens-Nether-Expansion#79]
When this mod is loaded together with some other mods, it results in unwanted arrow behavior. When using a bow (not a crossbow), arrows of any type (including modded) drop immediately at the point of their origin, instead of being launched by the bow.

The issue seems to be triggered when this mod is loaded together with [Enchantery](https://github.com/AstralOrdana/Enchantery) and an unknown combination of the following library mods:

- Blueprint
- Bookshelf
- Cerbon's API
- Citadel
- Collective
- Framework
- GeckoLib
- GeckolibIrisCompat
- Iceberg
- Necronomicon
- OctoLib
- Placebo
- Player Animator
- Puzzles Lib
- Resourceful Lib
- Rhino
- Searchables
- SuperMartijn642's Config Library
- YetAnotherConfigLib
- YUNG's API
- Zeta

I will elaborate further if I manage to find the exact culprits. So far, it seems to be caused by some specific combination of mods, rather than one specific library.

For example:
- The issue **does not** occur when only JNE, Enchantery and their respective dependencies (Architectury, Terrablender, Moonlight Lib) are loaded. It also **does not** occur when either JNE or Enchantery are not present, even with everything else loaded.
-  The issue **does** occur when JNE is only loaded together with Enchantery and Yet Another Config Lib (plus dependencies). However, removing YACL while loading all the other libraries does not solve the issue, which means this is not the only culprit.

Possibly related: _Shotgun-exclusive enchantments also seem to be obtainable when enchanting bows in the enchanting table._

**Mod version:** 2.1.0
**Game version:** 1.20.1
**Mod loader:** Forge 47.3.7

**Comment by ThatJadenXgamer** [comment]
test it on the new 2.1.1 version

**Comment by Jirickal** [comment]
I can confirm that the bug is no longer present in the new version. Thank you very much!
