### ISSUE TITLE
Issue with UnionLib-1.20.1-10.2.6-Forge

### ISSUE THREAD

**Issue by Ice-Baron** [ThatJadenXgamer/Jadens-Nether-Expansion#8]
On launch it crashes and a produces in the log: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector netherexp$modifyArrowVelocity(Lnet/minecraft/world/entity/projectile/AbstractArrow;Lnet/minecraft/world/entity/Entity;FFFFF)V in netherexp-common.mixins.json:item.BowItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap netherexp-common-refmap.json
I.E I think the mod is incompatible with survive due to the fact union lib is a dependency of survive

**Comment by ThatJadenXgamer** [comment]
UnionLib's code is not open source meaning I cannot figure out if it issue is being caused on my side or theirs
for now I'm going to mark this as **wontfix** but you should report this incompatibility to UnionLib as well
