### ISSUE TITLE
Crash during mod loading.

### ISSUE THREAD

**Issue by IAmJesusChrist** [ThatJadenXgamer/Jadens-Nether-Expansion#80]
Context: In a decently sized modpack, all the other mods work fine without JNE but doesn't when it's enabled.

Log: https://mclo.gs/AHlNztl#L44

**Comment by ThatJadenXgamer** [comment]
disable `redesigned_fireballs` in the config netherexp-common.toml file

it's some kind of incompatibility but due to the size of this modpack it's hard to tell which one is causing it
disabling that line in config fixes it though
