### ISSUE TITLE
The server crashed because of a problem with the mod.

### ISSUE THREAD

**Issue by HuangYanQwQ** [ThatJadenXgamer/Jadens-Nether-Expansion#81]
The crash report indicates a "Ticking entity" issue caused by a in the Minecraft mod "Jaden's Nether Expansion" (version 2.0.2). Specifically, the error arises in the class, line 550, where a object is unexpectedly during a method call. This typically means that an entity in the game tried to perform an action without all required data, leading to a crash when attempting to interact with a missing or unloaded entity​NullPointerExceptionEctoSlabAttackGoallivingEntitynull(crash-2024-11-08_18.28.…).

To potentially fix this, you could:

Update or Roll Back the Mod: Check for an update to "Jaden's Nether Expansion" or consider rolling back to a previous stable version if available.
Modify or Remove the Problematic Entity: Use commands to remove "Ecto Slab" entities from the affected area in the Nether (coordinates: 1023.15, 43.00, 1455.79).
Contact Mod Developer: If the error persists, report it to the developer with the crash details for further support.
[crash-2024-11-08_18.28.46-server.txt](https://github.com/user-attachments/files/17677219/crash-2024-11-08_18.28.46-server.txt)

**Comment by ThatJadenXgamer** [comment]
@HuangYanQwQ update the mod to latest 2.1.0 patch and see if the issue persists
