### ISSUE TITLE
Massive lag caused by AttackTreacherousCandleGoal.isValidTarget()

### ISSUE THREAD

**Issue by mateus3c** [ThatJadenXgamer/Jadens-Nether-Expansion#9]
https://spark.lucko.me/invXo0H3Fb

For some reason it's also interfering with Alex's Mobs Underminer, causing it to cause lag too

**Comment by ThatJadenXgamer** [comment]
It seems the block detection for finding a treacherous candle is causing some lag
I'll optimize the code so only mobs spawned by the treacherous candle have this goal
