### ISSUE TITLE
Missing texture of ectoplasm

### ISSUE THREAD

**Issue by SSWTLZZ** [ThatJadenXgamer/Jadens-Nether-Expansion#93]
The fluids in JEI and fluid containers are invisible, and the strange thing I discovered is shown in the video below.
https://github.com/user-attachments/assets/18a5df1e-0e3e-49e0-912e-851e4566e9a0

**Comment by ThatJadenXgamer** [comment]
Architectury Issue
it should be fixed soon now that JNE is becoming Forge-Exclusive

**Comment by ThatJadenXgamer** [comment]
Fixed in 2.1.4
