### ISSUE TITLE
[Bug] Brushing Ecto soul sand uses up durability for every click (sometimes more than 1), causing brushes to rapidly break

### ISSUE THREAD

**Issue by ambientNexus** [ThatJadenXgamer/Jadens-Nether-Expansion#96]
Unlike suspicious soul sand, brushing Ecto soul sand rapidly breaks brushes due to constantly taking durability, oftentimes seemingly ignoring unbreaking and even taking multiple durability points for one click. This causes brushes to break rapidly, especially since they only have 64 durability.

**Comment by ThatJadenXgamer** [comment]
that's intentional. brushing ecto soul sand is suppose to speed up the process of getting suspicious soul sand at the cost of durablity
if you don't want to constantly use up brushes then you should wait for the ecto soul sand to manually turn sus

**Comment by ambientNexus** [comment]
Ah, alright then. Just assumed based off of how quickly the durability was disappearing on an unbreaking 3 brush that there had to be some sort of issue.
